"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { toPng } from "html-to-image";
import {
  Boxes,
  Building2,
  Code2,
  Download,
  FolderKanban,
  GalleryVerticalEnd,
  Gem,
  Grid3x3,
  LayoutDashboard,
  Search,
  Sparkles,
  Star,
  Terminal,
  Trophy,
  Waves,
} from "lucide-react";
import { BentoGrid } from "./BentoGrid";
import { HoloCardView } from "./HoloCardView";
import { ProceduralCityEditor } from "./ProceduralCityEditor";
import { TerminalView } from "./TerminalView";
import type { GitBentoData } from "./types";

type AssetMode = "gitcity" | "bento" | "terminal" | "card";

const assetItems: {
  id: AssetMode;
  label: string;
  icon: typeof Building2;
  description: string;
  hint: string;
}[] = [
  {
    id: "gitcity",
    label: "GitCity",
    icon: Building2,
    description: "Procedural skyline generated from your live GitHub activity.",
    hint: "Use the in-preview Filter button for theme and camera controls.",
  },
  {
    id: "bento",
    label: "Bento Card",
    icon: Grid3x3,
    description: "Draggable profile grid with reusable visual templates.",
    hint: "Drag cards inside the canvas and switch built-in Bento themes.",
  },
  {
    id: "terminal",
    label: "Terminal Card",
    icon: Terminal,
    description: "Animated CLI snapshot built from your actual profile data.",
    hint: "Perfect for README drops, posts, and hacker-style share images.",
  },
  {
    id: "card",
    label: "Holo Card",
    icon: Boxes,
    description: "Interactive showcase card with tilt, glare, and live stats.",
    hint: "Mouse move par live holographic tilt effect trigger hota hai.",
  },
];

export function GitBentoApp({
  initialUsername = "",
  autoGenerate = false,
}: {
  initialUsername?: string;
  autoGenerate?: boolean;
}) {
  const [username, setUsername] = useState(initialUsername);
  const [data, setData] = useState<GitBentoData | null>(null);
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [activeAsset, setActiveAsset] = useState<AssetMode>("gitcity");
  const previewRef = useRef<HTMLDivElement>(null);
  const hasAutoGenerated = useRef(false);

  const activeConfig = assetItems.find((item) => item.id === activeAsset) ?? assetItems[0];
  const profileName = data?.profile.name || "Shashwat";
  const profileHandle = data?.profile.username || username || "shashwattcodes";
  const profileAvatar = data?.profile.avatar;
  const totalContributions = data?.contributionCalendar?.totalContributions ?? 0;
  const topLanguage = data?.topLanguages[0]?.name ?? "Mixed";
  const organizations = data?.organizations.slice(0, 3) ?? [];

  const rightPanelStats = useMemo(
    () => [
      { label: "Contributions", value: totalContributions ? totalContributions.toLocaleString() : "Live" },
      { label: "Repositories", value: data ? String(data.totals.publicRepos) : "--" },
      { label: "Top Language", value: data ? topLanguage : "--" },
      { label: "Longest Streak", value: data ? `${data.rpg.longestStreak} days` : "--" },
    ],
    [data, topLanguage, totalContributions],
  );

  async function generateProfile(value: string) {
    const trimmedUsername = value.trim();
    if (!trimmedUsername) {
      setError("Enter a GitHub username first.");
      return;
    }

    setIsLoading(true);
    setError("");

    try {
      const response = await fetch(
        `/api/github?username=${encodeURIComponent(trimmedUsername)}`,
      );
      const payload = await response.json();

      if (!response.ok) {
        setError(payload.error ?? "Something went wrong.");
        return;
      }

      setData(payload);
      window.localStorage.setItem("gitbento:last-username", trimmedUsername);
    } catch {
      setError("Network error. Please try again.");
    } finally {
      setIsLoading(false);
    }
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    await generateProfile(username);
  }

  useEffect(() => {
    if (!autoGenerate || !initialUsername || hasAutoGenerated.current) return;
    hasAutoGenerated.current = true;
    void generateProfile(initialUsername);
  }, [autoGenerate, initialUsername]);

  async function handleDownload() {
    if (!previewRef.current || !data) return;

    const dataUrl = await toPng(previewRef.current, {
      cacheBust: true,
      pixelRatio: 2,
      backgroundColor: "#0d1117",
    });

    const link = document.createElement("a");
    link.download = `${profileHandle}-${activeAsset}.png`;
    link.href = dataUrl;
    link.click();
  }

  return (
    <main className="gitcraft-dashboard">
      <aside className="dashboard-sidebar">
        <a className="dash-logo" href="/">
          <span><Code2 size={20} /></span>
          GitCraft
        </a>

        <button className="dash-create-button" type="button" onClick={() => setActiveAsset("gitcity")}>
          <Sparkles size={16} />
          Create New
        </button>

        <nav className="dash-nav">
          <a href="#"><LayoutDashboard size={16} /> Overview</a>
          <a href="#"><FolderKanban size={16} /> All Assets</a>
        </nav>

        <div className="dash-nav-group">
          <p>Generate</p>
          {assetItems.map((item) => {
            const Icon = item.icon;
            return (
              <button
                className={item.id === activeAsset ? "active" : ""}
                type="button"
                key={item.id}
                onClick={() => setActiveAsset(item.id)}
              >
                <Icon size={16} />
                {item.label}
              </button>
            );
          })}
        </div>

        <div className="dash-nav-group">
          <p>Library</p>
          <a href="#"><GalleryVerticalEnd size={16} /> Templates</a>
          <a href="#"><Star size={16} /> Themes</a>
        </div>

        <div className="sidebar-spacer" />

        <section className="premium-box">
          <Gem size={18} />
          <h3>Unlock Premium</h3>
          <p>High-res exports, more visual systems, and extra asset variations.</p>
          <button type="button">Upgrade Now</button>
        </section>

        <section className="sidebar-user">
          {profileAvatar ? <img src={profileAvatar} alt="" /> : <span>{profileName.slice(0, 1)}</span>}
          <div>
            <strong>{profileName}</strong>
            <small>@{profileHandle}</small>
          </div>
        </section>
      </aside>

      <section className="dashboard-main">
        <header className="dashboard-header">
          <div>
            <h1>{activeConfig.label}</h1>
            <p>{activeConfig.description}</p>
          </div>
          <div className="dashboard-actions">
            <form onSubmit={handleSubmit} className="dashboard-search">
              <Search size={15} />
              <input
                value={username}
                onChange={(event) => setUsername(event.target.value)}
                placeholder="Enter GitHub username"
              />
            </form>
            <button className="ghost-action" type="button">
              <Star size={15} />
              Star on GitHub
            </button>
            <button className="purple-action" type="button" onClick={handleDownload} disabled={!data}>
              <Download size={15} />
              Export
            </button>
          </div>
        </header>

        {error ? <p className="dashboard-error">{error}</p> : null}

        <section className="asset-switcher">
          {assetItems.map((item) => {
            const Icon = item.icon;
            return (
              <button
                className={item.id === activeAsset ? "selected" : ""}
                type="button"
                key={item.id}
                onClick={() => setActiveAsset(item.id)}
              >
                <Icon size={16} />
                <span>{item.label}</span>
              </button>
            );
          })}
        </section>

        <div className="asset-shell" ref={previewRef}>
          {!data && !isLoading ? (
            <section className="empty-stage">
              <span>Live Workspace</span>
              <h2>GitHub profile ko real asset engine ke saath render karte hain.</h2>
              <p>
                Search any username and we will plug actual GitCity, Bento, Terminal,
                and Holo views directly into this dashboard.
              </p>
            </section>
          ) : null}

          {isLoading ? (
            <section className="empty-stage">
              <span>Fetching Data</span>
              <h2>Refreshing your live GitCraft workspace...</h2>
              <p>Repositories, contribution history, and visual layers sync ho rahe hain.</p>
            </section>
          ) : null}

          {data ? (
            <section className="live-stage">
              {activeAsset === "gitcity" ? (
                <ProceduralCityEditor data={data} embedded />
              ) : null}
              {activeAsset === "bento" ? (
                <div className="component-stage"><BentoGrid data={data} /></div>
              ) : null}
              {activeAsset === "terminal" ? (
                <div className="component-stage"><TerminalView data={data} /></div>
              ) : null}
              {activeAsset === "card" ? (
                <div className="component-stage"><HoloCardView data={data} /></div>
              ) : null}
            </section>
          ) : null}
        </div>

        <section className="dashboard-section">
          <div className="section-title-row">
            <div>
              <h2>Available Functional Views</h2>
              <p>Ye sab static mock nahi, actual connected renderers hain.</p>
            </div>
          </div>
          <div className="template-strip">
            {assetItems.map((item) => {
              const Icon = item.icon;
              return (
                <button
                  className={`template-thumb functional ${item.id === activeAsset ? "selected" : ""}`}
                  type="button"
                  key={item.id}
                  onClick={() => setActiveAsset(item.id)}
                >
                  <span className="functional-icon"><Icon size={18} /></span>
                  <strong>{item.label}</strong>
                  <small>{item.hint}</small>
                </button>
              );
            })}
          </div>
        </section>

        <section className="dashboard-section">
          <div className="section-title-row">
            <div>
              <h2>Your Recently Generated</h2>
              <p>Quick jump cards for the real render modes we preserved.</p>
            </div>
          </div>
          <div className="recent-dashboard-grid">
            {assetItems.map((item) => {
              const Icon = item.icon;
              return (
                <button
                  className={`recent-dashboard-card recent-switch ${item.id === activeAsset ? "selected" : ""}`}
                  type="button"
                  key={item.id}
                  onClick={() => setActiveAsset(item.id)}
                >
                  <Icon size={18} />
                  <span>{item.label}</span>
                  <strong>@{profileHandle}</strong>
                </button>
              );
            })}
          </div>
        </section>
      </section>

      <aside className="customize-panel">
        <div className="customize-header">
          <div>
            <h2>Customize</h2>
            <p>Real functionality ko shell ke andar preserve kiya gaya hai.</p>
          </div>
          <Trophy size={18} />
        </div>

        <div className="control-block">
          <span>Active View</span>
          <div className="info-card">
            <strong>{activeConfig.label}</strong>
            <p>{activeConfig.hint}</p>
          </div>
        </div>

        <div className="control-block">
          <span>Profile Status</span>
          <div className="stats-stack">
            {rightPanelStats.map((item) => (
              <div className="stat-chip" key={item.label}>
                <small>{item.label}</small>
                <strong>{item.value}</strong>
              </div>
            ))}
          </div>
        </div>

        <div className="control-block">
          <span>Live Data</span>
          <div className="info-card">
            <strong>{data ? "Connected to GitHub data" : "Waiting for a username"}</strong>
            <p>
              {data
                ? `${data.topRepositories.length} top repos, ${data.recentActivity.length} recent events, and ${
                    data.topLanguages.length
                  } language signals loaded.`
                : "Profile fetch hone ke baad real renderers yahin data use karenge."}
            </p>
          </div>
        </div>

        <div className="control-block">
          <span>Organizations</span>
          <div className="org-list">
            {organizations.length ? (
              organizations.map((org) => (
                <div className="org-item" key={org.login}>
                  <img src={org.avatar} alt="" />
                  <strong>{org.login}</strong>
                </div>
              ))
            ) : (
              <div className="info-card compact">
                <strong>No org preview yet</strong>
                <p>Public organizations load hone par yahan show kar denge.</p>
              </div>
            )}
          </div>
        </div>

        <div className="control-block">
          <span>Quick Notes</span>
          <div className="notes-list">
            <div><Building2 size={15} /> GitCity keeps its own embedded filter panel.</div>
            <div><Grid3x3 size={15} /> Bento drag-and-drop is still active inside the view.</div>
            <div><Terminal size={15} /> Terminal animation still runs from live fetched data.</div>
            <div><Waves size={15} /> Holo card hover and glare behavior stays intact.</div>
          </div>
        </div>

        <button className="download-panel-button" type="button" onClick={handleDownload} disabled={!data}>
          <Download size={17} />
          Download Current View
        </button>
        <p className="free-download">Shared export attached to the currently active functional renderer.</p>
      </aside>
    </main>
  );
}
